config/routes.rb
Rails.application.routes.draw do
  # Serve websocket cable requests in-process
  mount ActionCable.server => '/cable'

  # scope '(:locale)' do
  # scope "(:locale)" do #, :locale => /en|ru/ do

  resources :themes
  # get 'work/index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'main#index'
  resources :values
  resources :images
  resources :microposts
  resources :users
  resources :sessions, only: [:new, :create, :destroy]

  # Api definition
  namespace :api, defaults: { format: :json } do
    # We are going to list our resources here
    #   resources :users

    match 'next_image',       to: 'api#next_image',   via: 'get'
    match 'prev_image',       to: 'api#prev_image',   via: 'get'
    match 'save_value',       to: 'api#save_value',   via: :get
  end

  match 'index',    to: 'main#index',           via: 'get'
  match 'about',    to: 'main#about',           via: 'get'
  match 'help',     to: 'main#help',            via: 'get'
  match 'contacts', to: 'main#contacts',        via: 'get'

  match 'work',             to: 'work#index',             via: 'get'
  match 'choose_image',     to: 'work#choose_image',      via: :get
  match 'choose_theme',     to: 'work#choose_theme',      via: :get
  match 'display_theme',    to: 'work#display_theme',     via: :post
  # match 'next_image',       to: 'work#next_image',   via: 'get'

  # match 'prev_image',       to: 'work#prev_image',   via: 'get'
  match 'results_list',     to: 'work#results_list', via: :get
  # match 'save_value',       to: 'work#save_value',      via: :get

  # api
  # match 'next_image',       to: 'api/api#next_image',   via: 'get'
  # match 'prev_image',       to: 'api/api#prev_image',   via: 'get'
  match 'save_value',       to: 'api/api#save_value',   via: :get

  match 'signup',   to: 'users#new',            via: 'get'
  match 'signin',   to: 'sessions#new',         via: 'get'
  match 'signout',  to: 'sessions#destroy',     via: 'delete'


end

app/controllers/main_controller.rb
class MainController < ApplicationController
  require 'json'
  
  
  
  def index
  
    @tasks = "index"
    respond_to  :json, :html
  
    # respond_to do |format|
    #   format.html
    #   format.json
    # end
  end


  def help
    @current_user = current_user
  end

  def contacts
    @current_user = current_user
  end
  
  def about
    @current_user = current_user
  end

end

app/helpers/main_helper.rb
module MainHelper
end

app/views/main/_app_dev_notice.html.haml
%p{style: " font-size: 1em; position: relative; left: 40%;"}
  %span{ style: "color: #730E15; font-size: 1.3em; position: relative; left: 11%;" }    
    App is in Progress/Maintenance

app/views/main/about.html.haml
- provide(:title, "About")

%h1= t('.about_title')

.about-copy
  %h1.list
    Приложение Expertise предназначено для сбора оценок предпочтений пользователей.
    %br
    Пользователи выступают в роли экспертов. Их мнение крайне важно для экспертного сообщества.
    %br
    На основе частных мнений экспертов вычисляется средняя квалифицированная оценка.
    %br
    Собранные в данном приложении данные представляют интерес как для самих экспертов,
    так и для сторонних организаций и пользователей, занятых, например, в сфере маркетинга и изучения рынков.
  -#%p
  -#  A few reasons why this product is worth using, what it is for and why you need it.
  -#  %br
  -#  First wide reason and second short reason.

app/views/main/contacts.html.haml
- provide(:title, "Contacts")

%h1= t('.contacts_title')

.about-copy
  %h1.list
    App is in development

app/views/main/help.html.haml
- provide(:title, "Help")

.about-app
  - if signed_in?
    %h1.about-app-title
      Приветствуем Вас,  #{@current_user.name.inspect} !
      -##{@current_user.email.inspect}

  %h2
    Пользовательский интерфейс Expertise построен по принципу "одностраничного приложения".
    %br
    Это существенно упрощает взаимодействие пользователей с приложением.
  %br
  %h2
    Основные шаги.
  %div.about-app-content
    %div
      1. Регистрация нового пользователя. Это необходимо для получения доступа к сервису.
    %div
      2. Если пользователь зарегистрирован, то ему необходимо войти на сайт - sign in.
    %div
      3. Прежде всего нужно выбрать тему, по которой пользователь намерен оставить свои оценки. Выбрав тему из списка, пользователь получает доступ к списку изображений.

    %div
      4. Пользователь оценивает предъявляемые на экране изображения, выбирая желаемое значение на шкале оценок.
    %div
      5. На экране отображается усредненная оценка всех экспертов, участвовавших в опросе по данному изображению на выбранную тему. А также общее количество всех оценок на сайте.
    %div
      6. Имеется возможность просмотра итоговых оценок по всем изображениям на выбранную тему.

app/views/main/index.en.html.haml
- content_for(:title,  "Index")


.center.jumbotron
  %h1
    Welcome!
    %br
    %br
    %h2
      To continue - press:
  - if signed_in?
    = link_to "Application", work_path, class: "btn app-button"
  - else
    = link_to "Sign up", signup_path, class: "btn app-button"


-#.app_notice
-#  = render 'main/app_dev_notice'


-#
-#= link_to image_tag("rails.png", alt: "Rails logo"), |
-#  'http://rubyonrails.org/'

app/views/main/index.ru.html.haml
- content_for(:title,  "Index")


.center.jumbotron
  %h1
    Добро пожаловать!
    %br
    %br
    %h2
      Чтобы продолжить - нажми:
  - if signed_in?
    = link_to "Приложение", work_path, class: "btn app-button"
  - else
    = link_to "Регистрация", signup_path, class: "btn app-button"