config/routes.rb
Rails.application.routes.draw do
  # Serve websocket cable requests in-process
  mount ActionCable.server => '/cable'

  # scope '(:locale)' do
  # scope "(:locale)" do #, :locale => /en|ru/ do

  resources :themes
  # get 'work/index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'main#index'
  resources :values
  resources :images
  resources :microposts
  resources :users
  resources :sessions, only: [:new, :create, :destroy]

  # Api definition
  namespace :api, defaults: { format: :json } do
    # We are going to list our resources here
    #   resources :users

    match 'next_image',       to: 'api#next_image',   via: 'get'
    match 'prev_image',       to: 'api#prev_image',   via: 'get'
    match 'save_value',       to: 'api#save_value',   via: :get
  end

  match 'index',    to: 'main#index',           via: 'get'
  match 'about',    to: 'main#about',           via: 'get'
  match 'help',     to: 'main#help',            via: 'get'
  match 'contacts', to: 'main#contacts',        via: 'get'

  match 'work',             to: 'work#index',             via: 'get'
  match 'choose_image',     to: 'work#choose_image',      via: :get
  match 'choose_theme',     to: 'work#choose_theme',      via: :get
  match 'display_theme',    to: 'work#display_theme',     via: :post
  # match 'next_image',       to: 'work#next_image',   via: 'get'

  # match 'prev_image',       to: 'work#prev_image',   via: 'get'
  match 'results_list',     to: 'work#results_list', via: :get
  # match 'save_value',       to: 'work#save_value',      via: :get

  # api
  # match 'next_image',       to: 'api/api#next_image',   via: 'get'
  # match 'prev_image',       to: 'api/api#prev_image',   via: 'get'
  match 'save_value',       to: 'api/api#save_value',   via: :get

  match 'signup',   to: 'users#new',            via: 'get'
  match 'signin',   to: 'sessions#new',         via: 'get'
  match 'signout',  to: 'sessions#destroy',     via: 'delete'


end

app/models/user.rb
class User < ApplicationRecord

  has_many :microposts, dependent: :destroy
  has_many :values, dependent: :destroy

  before_save { self.email = email.downcase }
  before_create :create_remember_token

  validates :name, presence: true, uniqueness: true, length: { maximum: 50 }
  # validates :email, presence: true, uniqueness: true, length: { maximum: 50 }

  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-]+(\.[a-z]+)*\.[a-z]+\z/i
  validates :email, presence: true,
            uniqueness: { case_sensitive: false },
            format: { with: VALID_EMAIL_REGEX }

 # has_secure_password
  validates :password, length: { minimum: 6 }

  def User.new_remember_token
    SecureRandom.urlsafe_base64
  end

  def User.encrypt(token)
    Digest::SHA1.hexdigest(token.to_s)
  end

  private

  def create_remember_token
    self.remember_token = User.encrypt(User.new_remember_token)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]
  
  # GET /users
  # GET /users.json
  def index
    # @users = User.all
    # expires_in 5.minutes
    # sleep 15e

    @users = User.all
    # @stats = Rails.cache.stats.first.last
  end

  # GET /users/1
  # GET /users/1.json
  # SERIALIZED !! FOR API DEMONSTRATION
  def show
    user = User.find(params[:id])
    # render json: user
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(user_params)
    respond_to do |format|
     if @user.save
        sign_in @user
        flash.now[:notice] = "Welcome to the Experteese - sample App!"
        format.html { redirect_to @user, notice: 'User was successfully created.' }
        format.json { render :show, status: :created, location: @user }
      else
        flash.now[:alert] = "Bad registration"
        format.html { render :new }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url, notice: 'User was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      params.require(:user).permit(:name, :email, :password, :password_confirmation)
    end
end

app/helpers/users_helper.rb
module UsersHelper
  
  # Returns the Gravatar (http://gravatar.com/) for the given user.
  def gravatar_for(user)
    gravatar_id = Digest::MD5::hexdigest(user.email.downcase)
    gravatar_url = "https://secure.gravatar.com/avatar/#{gravatar_id}"
    image_tag(gravatar_url, alt: user.name, class: "gravatar")
  end


end

app/views/users/_form.html.haml
%div{:style=>"padding:50px; margin-top:-50px;"}
  = form_for @user do |f|
    - if @user.errors.any?
      #error_explanation
        %h2= "#{pluralize(@user.errors.count, "error")} prohibited this user from being saved:"
        %ul
          - @user.errors.full_messages.each do |msg|
            %li= msg

    .field
      = f.label t('.name')
      = f.text_field :name
    .field
      = f.label t('.email')
      = f.text_field :email
    .field
      = f.label t('.password')
      = f.password_field :password
    .field
      = f.label t('.password_confirmation')
      = f.password_field :password_confirmation


    .actions
      -#= f.submit 'Save'
      = f.submit t(".create_account"), class: "btn app-button"

app/views/users/edit.html.haml
%h1 Editing user

= render 'form'

= link_to 'Show', @user
\|
= link_to 'Back', users_path

app/views/users/index.html.haml
%div.all-users

  %h1 Список пользователей

  %table
    %thead
      %tr
        %th Имя
        %th Эл.почта
        %th
        %th
        %th

    %tbody
      - @users.each do |user|
        %tr
          %td= user.name
          %td= user.email
          %td= link_to 'Показать', user
          %td= link_to 'Редактировать', edit_user_path(user)
          %td= link_to 'Удалить', user, :method => :delete, :data => { :confirm => 'Are you sure?' }

  = link_to 'Новый пользователь', new_user_path, :class => "btn app-button"

app/views/users/new.html.haml
- provide(:title, "Sign up")

%h1.new_user-title{:style=>"margin-top:50px;"}
  = t('.new_user_sign_up')

= render 'form'

= link_to t('.back'), root_path, :class => "back-link"

app/views/users/show.html.haml
- provide(:title, @user.name)
-#%p#notice= notice


.show-user
  %div.show-user__name
    = gravatar_for @user
    = @user.name

  %div.show-user__mail
    %b= t('.email')
    = @user.email

  = link_to t('.work'), work_path, class: "btn app-button"