config/routes.rb
Rails.application.routes.draw do
  # Serve websocket cable requests in-process
  mount ActionCable.server => '/cable'

  # scope '(:locale)' do
  # scope "(:locale)" do #, :locale => /en|ru/ do

  resources :themes
  # get 'work/index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'main#index'
  resources :values
  resources :images
  resources :microposts
  resources :users
  resources :sessions, only: [:new, :create, :destroy]

  # Api definition
  namespace :api, defaults: { format: :json } do
    # We are going to list our resources here
    #   resources :users

    match 'next_image',       to: 'api#next_image',   via: 'get'
    match 'prev_image',       to: 'api#prev_image',   via: 'get'
    match 'save_value',       to: 'api#save_value',   via: :get
  end

  match 'index',    to: 'main#index',           via: 'get'
  match 'about',    to: 'main#about',           via: 'get'
  match 'help',     to: 'main#help',            via: 'get'
  match 'contacts', to: 'main#contacts',        via: 'get'

  match 'work',             to: 'work#index',             via: 'get'
  match 'choose_image',     to: 'work#choose_image',      via: :get
  match 'choose_theme',     to: 'work#choose_theme',      via: :get
  match 'display_theme',    to: 'work#display_theme',     via: :post
  # match 'next_image',       to: 'work#next_image',   via: 'get'

  # match 'prev_image',       to: 'work#prev_image',   via: 'get'
  match 'results_list',     to: 'work#results_list', via: :get
  # match 'save_value',       to: 'work#save_value',      via: :get

  # api
  # match 'next_image',       to: 'api/api#next_image',   via: 'get'
  # match 'prev_image',       to: 'api/api#prev_image',   via: 'get'
  match 'save_value',       to: 'api/api#save_value',   via: :get

  match 'signup',   to: 'users#new',            via: 'get'
  match 'signin',   to: 'sessions#new',         via: 'get'
  match 'signout',  to: 'sessions#destroy',     via: 'delete'


end

app/views/shared/_flash.html.haml
-#- flash.each do |type, message|
-#  .flash{class: type}
-#    = message

- flash.each do |type, message|
  - if type == 'link'
    .flash{class: message[:type]}
      .container
        = link_to message[:message], message[:link]
        %a.close{href:'#', onclick: "$('.flash').slideUp();"}= fa_icon "close"
  - else
    :javascript
      Notification.#{type}("#{message}")

    .flash{class: type}
      .container
        = message
        %a.close{href:'#', onclick: "$('.flash').slideUp();"}= fa_icon "close"

app/views/shared/_footer.html.haml
%footer.footer
  %div.footer__copyright
    %span.author
    = t ('Copyright © NaniLevi')
    %div{:style => "margin-top:-150px;" }
      %a{:href =>"http://www.brainlook.org", :style=>"text-decoration:none; color:fff;"}
        %img{:alt => "Share to Brainlook", :src => "/assets/BL.png", :title => "Brainlook", :style=>"width:150px;" }
        %div{:style => "margin-left:40px; margin-top:-40px; color:#fff;"}
          = t(".share_opinion")
  .bin_nav
    = link_to t('.about'), about_path
    = link_to t('.contacts'), contacts_path

app/views/shared/_header.html.haml
%header.navbar.header
  .logo{:style=>" width: 35%; margin-left: -110px;"}
    = link_to image_tag("/assets/ruby.png", alt: "Rails logo")
    %div{:style=>"margin-top: -150px; margin-left: 107px;"}
      = link_to t('.logo_title'), root_path, class: "header__logo"
  %nav.header__menu
    %ul.header__menu-list
      %li.header__menu-link
        = link_to t('.help'), help_path
      - if signed_in?
        %li.logged.header__menu-link
          %div#fat-menu.dropdown
            %a.dropdown-toggle{"data-toggle" => "dropdown", :href => "#"}
              = gravatar_for current_user
              %p
                #{current_user.name}
                %b.caret
            %ul.dropdown-menu
              %li= link_to t('.profile'), current_user
              -#%li= link_to t('.settings'), '#'
              %li.divider
              %li
                = link_to t('.sign_out'), signout_path, method: "delete"
      - else
        %li.header__menu-link
          = link_to t('.sign_in'), signin_path
  %div.locale
    = link_to image_tag("Russia.jpg", alt: "",  style: "width: 10%; height: 10%", title: "Русский" ), locale: :ru
    = link_to image_tag("USA.jpg", alt: "",  style: "width: 12%; height: 12%", title: "English"), locale: :en
    %b
      = I18n.locale